@startuml
title UML-Activity.puml

start

:Спортсмен може переглядата наступні тренувальні програми ; 

if (Спортсмен обрав належну тренувальну програму?) then (yes)
  :Отримує повідомлення про наступні тренування;
stop
else (no)
  :Взіємодіє з експертами,щоб задати технічні або тренувальні запитання;

stop
@enduml
