@startuml
title Usecase

left to right direction

actor Спортсмен

rectangle Software {

    
    usecase (Сповістити спортсмена через онлайн повідомлення)
    usecase (Отримати сповіщення про наступну тренувальну програму)


   (Отримати сповіщення про наступну тренувальну програму) .> (Сповістити спортсмена через онлайн повідомлення) : include


   Спортсмен -- (Сповістити спортсмена через онлайн повідомлення)
   Спортсмен -- (Отримати сповіщення про наступну тренувальну програму)
}
@enduml
